default: &default
  adapter: postgresql
  encoding: utf8
  charset: utf8
  pool: 5
  username: mrej
  password: khongnho
  host: 127.0.0.1
  port: 5432

development:
  <<: *default
  database: example_app_rails_development

test:
  <<: *default
  database: example_app_rails_test